export const DEFAULT_ROWS: Record<string, string>[] = [
  {
    "Reporting starts": "2026-10-01",
    "Reporting ends": "2026-10-04",
    "Ad name": "Ads01",
    "Ad delivery": "active",
    "Results": "1",
    "Result indicator": "actions:offsite_conversion.fb_pixel_purchase",
    "Cost per results": "1072982",
    "Ad set budget": "Using campaign budget",
    "Ad set budget type": "0",
    "Amount spent (IDR)": "1072982",
    "Impressions": "11774",
    "Reach": "9655",
    "Ends": "Ongoing",
    "Attribution setting": "7-day click, 1-day view or 1-day engaged view",
    "Bid": "0",
    "Bid type": "ABSOLUTE_OCPM",
    "Last significant edit": "2026-10-01T13:00:54+0700",
    "Quality ranking": "Average",
    "Engagement rate ranking": "Above average",
    "Conversion rate ranking": "Below average – bottom 35% of ads",
    "Ad set name": "Broad ALL kecuali papua",
    "Landing page views": "143",
    "Adds to cart": "21",
    "custom_derived_metrics:28766179969665315": "0.14685315",
    "Contacts": "12",
    "Cost per contact (IDR)": "89415.166667",
    "Landing page views rate per link clicks": "85.628743",
    "Purchases": "1",
    "Cost per purchase (IDR)": "1072982",
    "Purchase ROAS (return on ad spend)": "0.922662",
    "Results (initial)": "",
    "Results (initial) indicator": ""
  },
  {
    "Reporting starts": "2026-10-01",
    "Reporting ends": "2026-10-04",
    "Ad name": "Ads02",
    "Ad delivery": "active",
    "Results": "4",
    "Result indicator": "actions:offsite_conversion.fb_pixel_purchase",
    "Cost per results": "498983",
    "Ad set budget": "Using campaign budget",
    "Ad set budget type": "0",
    "Amount spent (IDR)": "1995932",
    "Impressions": "50236",
    "Reach": "39466",
    "Ends": "Ongoing",
    "Attribution setting": "7-day click, 1-day view or 1-day engaged view",
    "Bid": "0",
    "Bid type": "ABSOLUTE_OCPM",
    "Last significant edit": "2026-10-01T13:00:54+0700",
    "Quality ranking": "Below average – bottom 35% of ads",
    "Engagement rate ranking": "Above average",
    "Conversion rate ranking": "Below average – bottom 35% of ads",
    "Ad set name": "Broad ALL kecuali papua",
    "Landing page views": "411",
    "Adds to cart": "63",
    "custom_derived_metrics:28766179969665315": "0.15328467",
    "Contacts": "26",
    "Cost per contact (IDR)": "76766.615385",
    "Landing page views rate per link clicks": "82.2",
    "Purchases": "4",
    "Cost per purchase (IDR)": "498983",
    "Purchase ROAS (return on ad spend)": "1.984036",
    "Results (initial)": "",
    "Results (initial) indicator": ""
  },
  {
    "Reporting starts": "2026-10-01",
    "Reporting ends": "2026-10-04",
    "Ad name": "Ads03",
    "Ad delivery": "active",
    "Results": "",
    "Result indicator": "",
    "Cost per results": "",
    "Ad set budget": "Using campaign budget",
    "Ad set budget type": "0",
    "Amount spent (IDR)": "82213",
    "Impressions": "1574",
    "Reach": "1232",
    "Ends": "Ongoing",
    "Attribution setting": "7-day click, 1-day view or 1-day engaged view",
    "Bid": "0",
    "Bid type": "ABSOLUTE_OCPM",
    "Last significant edit": "2026-10-01T13:00:54+0700",
    "Quality ranking": "-",
    "Engagement rate ranking": "-",
    "Conversion rate ranking": "-",
    "Ad set name": "Broad ALL kecuali papua",
    "Landing page views": "26",
    "Adds to cart": "5",
    "custom_derived_metrics:28766179969665315": "0.19230769",
    "Contacts": "2",
    "Cost per contact (IDR)": "41106.5",
    "Landing page views rate per link clicks": "72.222222",
    "Purchases": "",
    "Cost per purchase (IDR)": "",
    "Purchase ROAS (return on ad spend)": "",
    "Results (initial)": "",
    "Results (initial) indicator": ""
  },
  {
    "Reporting starts": "2026-10-01",
    "Reporting ends": "2026-10-04",
    "Ad name": "Ads04",
    "Ad delivery": "active",
    "Results": "",
    "Result indicator": "",
    "Cost per results": "",
    "Ad set budget": "Using campaign budget",
    "Ad set budget type": "0",
    "Amount spent (IDR)": "6309",
    "Impressions": "265",
    "Reach": "187",
    "Ends": "Ongoing",
    "Attribution setting": "7-day click, 1-day view or 1-day engaged view",
    "Bid": "0",
    "Bid type": "ABSOLUTE_OCPM",
    "Last significant edit": "2026-10-01T13:00:54+0700",
    "Quality ranking": "-",
    "Engagement rate ranking": "-",
    "Conversion rate ranking": "-",
    "Ad set name": "Broad ALL kecuali papua",
    "Landing page views": "4",
    "Adds to cart": "",
    "custom_derived_metrics:28766179969665315": "0",
    "Contacts": "",
    "Cost per contact (IDR)": "",
    "Landing page views rate per link clicks": "100",
    "Purchases": "",
    "Cost per purchase (IDR)": "",
    "Purchase ROAS (return on ad spend)": "",
    "Results (initial)": "",
    "Results (initial) indicator": ""
  },
  {
    "Reporting starts": "2026-10-01",
    "Reporting ends": "2026-10-04",
    "Ad name": "Ads05",
    "Ad delivery": "active",
    "Results": "",
    "Result indicator": "",
    "Cost per results": "",
    "Ad set budget": "Using campaign budget",
    "Ad set budget type": "0",
    "Amount spent (IDR)": "146062",
    "Impressions": "5193",
    "Reach": "4369",
    "Ends": "Ongoing",
    "Attribution setting": "7-day click, 1-day view or 1-day engaged view",
    "Bid": "0",
    "Bid type": "ABSOLUTE_OCPM",
    "Last significant edit": "2026-10-01T13:00:54+0700",
    "Quality ranking": "-",
    "Engagement rate ranking": "-",
    "Conversion rate ranking": "-",
    "Ad set name": "Broad ALL kecuali papua",
    "Landing page views": "56",
    "Adds to cart": "3",
    "custom_derived_metrics:28766179969665315": "0.05357143",
    "Contacts": "2",
    "Cost per contact (IDR)": "73031",
    "Landing page views rate per link clicks": "75.675676",
    "Purchases": "",
    "Cost per purchase (IDR)": "",
    "Purchase ROAS (return on ad spend)": "",
    "Results (initial)": "",
    "Results (initial) indicator": ""
  },
  {
    "Reporting starts": "2026-10-01",
    "Reporting ends": "2026-10-04",
    "Ad name": "Ads06",
    "Ad delivery": "active",
    "Results": "2",
    "Result indicator": "actions:offsite_conversion.fb_pixel_purchase",
    "Cost per results": "182876.5",
    "Ad set budget": "Using campaign budget",
    "Ad set budget type": "0",
    "Amount spent (IDR)": "365753",
    "Impressions": "4849",
    "Reach": "3502",
    "Ends": "Ongoing",
    "Attribution setting": "7-day click, 1-day view or 1-day engaged view",
    "Bid": "0",
    "Bid type": "ABSOLUTE_OCPM",
    "Last significant edit": "2026-10-01T13:00:54+0700",
    "Quality ranking": "-",
    "Engagement rate ranking": "-",
    "Conversion rate ranking": "-",
    "Ad set name": "Broad ALL kecuali papua",
    "Landing page views": "45",
    "Adds to cart": "6",
    "custom_derived_metrics:28766179969665315": "0.13333333",
    "Contacts": "5",
    "Cost per contact (IDR)": "73150.6",
    "Landing page views rate per link clicks": "91.836735",
    "Purchases": "2",
    "Cost per purchase (IDR)": "182876.5",
    "Purchase ROAS (return on ad spend)": "5.413489",
    "Results (initial)": "",
    "Results (initial) indicator": ""
  }
];

export const DEFAULT_ANALYSIS = "# 📊 Dashboard Analisis Meta Ads — SVO BISNISHACK\n**Periode: 1–4 Oktober 2026 | Ad Set: Broad ALL kecuali Papua**\n\n---\n\n## 1. RINGKASAN PERFORMA KESELURUHAN\n\n### 💰 Metrik Utama\n\n| Metrik | Nilai |\n|---|---|\n| **Total Spend** | Rp 3.669.251 |\n| **Total Purchases** | 7 |\n| **Avg CPA (Cost/Purchase)** | Rp 524.179 |\n| **Blended ROAS** | ~1,91× *(estimasi dari weighted ROAS)* |\n| **Total Impressions** | 73.891 |\n| **Total Reach** | 58.411 |\n| **Frequency** | 1,26× |\n\n### 🔽 Analisis Funnel (Agregat)\n\n| Stage | Volume | Rate ke Stage Berikutnya |\n|---|---|---|\n| **Landing Page Views** | 685 | — |\n| **Adds to Cart** | 98 | **14,31%** (LPV → ATC) |\n| **Contacts** | 47 | **47,96%** (ATC → Contact) |\n| **Purchases** | 7 | **14,89%** (Contact → Purchase) |\n\n**Funnel end-to-end: LPV → Purchase = 1,02%**\n\n> ⚠️ **Bottleneck terbesar:** Contact → Purchase (hanya 14,89%). Dari 47 orang yang kontak, cuma 7 yang beli. Ini menunjukkan masalah di **closing/follow-up/offer**, bukan traffic.\n\n---\n\n## 2. RANKING IKLAN: TERBAIK → TERBURUK\n\n### 🏆 #1 — Ads06 (⭐ WINNER)\n\n| Metrik | Nilai |\n|---|---|\n| Spend | Rp 365.753 |\n| Purchases | 2 |\n| CPA | **Rp 182.877** ✅ terendah |\n| ROAS | **5,41×** ✅ tertinggi |\n| LPV → ATC | 13,33% (6/45) |\n| ATC → Contact | 83,33% (5/6) |\n| Contact → Purchase | 40,00% (2/5) |\n| CPM | Rp 75.426 |\n\n> **Verdict:** CPA paling murah, ROAS paling tinggi. Conversion rate contact→purchase terbaik di 40%. **Siap di-scale.**\n\n---\n\n### 🥈 #2 — Ads02 (POTENTIAL — Volume Terbesar)\n\n| Metrik | Nilai |\n|---|---|\n| Spend | Rp 1.995.932 |\n| Purchases | 4 |\n| CPA | **Rp 498.983** |\n| ROAS | **1,98×** |\n| LPV → ATC | 15,33% (63/411) ✅ terbaik |\n| ATC → Contact | 41,27% (26/63) |\n| Contact → Purchase | 15,38% (4/26) |\n| CPM | Rp 39.733 |\n| Quality | Below average ⚠️ |\n| Engagement | Above average ✅ |\n| Conversion | Below average ⚠️ |\n\n> **Verdict:** Volume paling besar, CPM paling efisien, ATC rate tertinggi. Tapi conversion lemah → 26 kontak hanya 4 beli. Butuh optimasi closing. **Pertahankan, perbaiki.**\n\n---\n\n### 🥉 #3 — Ads03 (LEARNING — Data Belum Cukup)\n\n| Metrik | Nilai |\n|---|---|\n| Spend | Rp 82.213 |\n| Purchases | 0 |\n| CPA | — |\n| ROAS | 0 |\n| LPV → ATC | **19,23%** (5/26) ✅ tertinggi! |\n| ATC → Contact | 40,00% (2/5) |\n| Contact → Purchase | 0% (0/2) |\n| Cost/Contact | Rp 41.107 ✅ termurah |\n\n> **Verdict:** Spend masih terlalu kecil untuk menilai. Tapi sinyal awal bagus — ATC rate tertinggi & cost/contact termurah. **Beri budget tambahan untuk testing.**\n\n---\n\n### #4 — Ads01 (UNDERPERFORMER)\n\n| Metrik | Nilai |\n|---|---|\n| Spend | Rp 1.072.982 |\n| Purchases | 1 |\n| CPA | **Rp 1.072.982** ❌ tertinggi |\n| ROAS | **0,92×** ❌ rugi |\n| LPV → ATC | 14,69% (21/143) |\n| ATC → Contact | 57,14% (12/21) |\n| Contact → Purchase | **8,33%** (1/12) ❌ |\n| Quality | Average |\n| Engagement | Above average ✅ |\n| Conversion | Below average ❌ |\n\n> **Verdict:** Sudah spend >1 juta, ROAS di bawah 1× (rugi). Engagement bagus tapi gagal convert. 12 orang kontak hanya 1 beli. **Matikan atau overhaul total.**\n\n---\n\n### #5 — Ads05 (UNDERPERFORMER)\n\n| Metrik | Nilai |\n|---|---|\n| Spend | Rp 146.062 |\n| Purchases | 0 |\n| ROAS | 0 |\n| LPV → ATC | 5,36% (3/56) ❌ terendah |\n| ATC → Contact | 66,67% (2/3) |\n| Contact → Purchase | 0% |\n\n> **Verdict:** ATC rate sangat rendah (5,36%). Landing page atau offer tidak resonan dengan audience dari ad ini. **Matikan.**\n\n---\n\n### #6 — Ads04 (DEAD — Tidak Ada Data)\n\n| Metrik | Nilai |\n|---|---|\n| Spend | Rp 6.309 |\n| Semua konversi | 0 |\n\n> **Verdict:** Terlalu kecil, nol konversi. Kemungkinan sudah auto-throttled oleh Meta. **Matikan.**\n\n---\n\n## 3. DIAGNOSA MASALAH UTAMA\n\n### 🔴 Masalah #1: CLOSING / FOLLOW-UP (PALING KRITIS)\n\n```\n47 orang KONTAK → hanya 7 PURCHASE (14,89%)\n```\n\n- Ini **bukan masalah iklan**, ini masalah **setelah klik**.\n- Kemungkinan: respons CS lambat, script closing lemah, tidak ada urgency/incentive saat follow-up, atau harga terasa mahal setelah kontak.\n- **Ads06 close 40%** vs **Ads01 close 8,33%** → kemungkinan segmen audience atau timing kontak berbeda.\n\n### 🟡 Masalah #2: CONVERSION RATE RANKING META (Below Average)\n\n- Ads01 & Ads02 sama-sama ditandai **\"Below average – bottom 35%\"** di conversion.\n- Artinya Meta pixel mendeteksi bahwa orang yang klik iklan ini **tidak menyelesaikan action** secara konsisten.\n- Dampak: Meta akan charge CPM lebih mahal & distribusi menurun seiring waktu.\n\n### 🟡 Masalah #3: QUALITY SCORE Ads02 (Below Average)\n\n- Ads02 punya volume terbesar tapi quality **below average**.\n- Ini biasanya sinyal: **kreaitf dianggap \"spammy\" atau misleading** oleh audience (hide/report).\n- Ironisnya engagement above average → orang react/comment tapi juga banyak yang negatif.\n\n### 🟢 Masalah #4: LANDING PAGE (Moderat)\n\n- LPV → ATC rata-rata 14,31% — **cukup OK** untuk e-commerce Indonesia.\n- Kecuali Ads05 (5,36%) — kemungkinan mismatch antara pesan iklan dan landing page.\n\n---\n\n## 4. ACTION PLAN — BESOK PAGI\n\n### ✅ SCALE: Ads06\n\n| Action | Detail |\n|---|---|\n| **Naikkan budget** | Dari saat ini → **Rp 250.000–350.000/hari** (gradual, naikkan 20-30% per hari, jangan langsung 2×) |\n| **Pantau** | Jika CPA tetap < Rp 250.000 setelah 3 hari, scale lagi ke Rp 500.000/hari |\n| **Duplikasi** | Buat 1 duplicate ad set dengan budget terpisah untuk test stabilitas |\n\n### ✅ BERI BUDGET TEST: Ads03\n\n| Action | Detail |\n|---|---|\n| **Alokasi** | **Rp 150.000–200.000/hari** selama 3-4 hari |\n| **Target** | Kumpulkan minimal 5-8 contacts untuk validasi apakah bisa convert |\n| **Kill trigger** | Jika setelah spend Rp 500.000 total masih 0 purchase → matikan |\n\n### ⚠️ PERTAHANKAN DENGAN CATATAN: Ads02\n\n| Action | Detail |\n|---|---|\n| **Jangan naikkan budget**, pertahankan di level saat ini (~Rp 500.000/hari) |\n| **Buat variasi kreatif baru** (Ads02-B) untuk perbaiki quality score — ubah hook pertama 3 detik, kurangi elemen clickbait |\n| **Fokus perbaiki closing rate** — 26 contacts tapi hanya 4 purchase |\n\n### 🛑 MATIKAN: Ads01, Ads04, Ads05\n\n| Ad | Alasan |\n|---|---|\n| **Ads01** | CPA Rp 1.072.982, ROAS 0,92× (rugi). Spend sudah >1 juta, data cukup untuk conclude: **gagal.** |\n| **Ads04** | Nol konversi, throttled. Tidak ada sinyal positif. |\n| **Ads05** | ATC rate 5,36% — audience tidak tertarik setelah klik. Nol purchase. |\n\n### 📋 Budget Rekomendasi Harian (Total ~Rp 900.000–1.050.000/hari)\n\n| Ad | Budget/Hari |\n|---|---|\n| Ads06 (scale) | Rp 300.000 |\n| Ads02 (maintain) | Rp 500.000 |\n| Ads03 (test) | Rp 150.000 |\n| Ads01, 04, 05 | **Rp 0 (OFF)** |\n| **Total** | **~Rp 950.000/hari** |\n\n> Sebelumnya spend rata-rata ~Rp 917.000/hari (Rp 3,67jt / 4 hari) → budget relatif sama, tapi **alokasi jauh lebih efisien**.\n\n---\n\n### 🧪 Langkah Testing Berikutnya (Minggu Depan)\n\n| Prioritas | Test | Detail |\n|\n| Prioritas | Test | Detail |\n|---|---|---|\n| **#1** | **Hook Kreatif Ads06** | Bikin 2–3 variasi video hook baru (format UGC/problem-solution) menggunakan angle yang sama dengan Ads06. |\n| **#2** | **SOP Closing CS / Follow-up** | Testing script follow-up WhatsApp dalam 5 menit pertama setelah contact masuk untuk mendongkrak contact→purchase dari 14,8% ke >25%. |\n| **#3** | **Revamp Hook Ads02** | Uji coba opening tanpa clickbait untuk memperbaiki Quality Ranking Meta dari *Below Average* ke *Average*. |";
